import React, { useState } from 'react'
import { SECTIONS, entriesFor } from '../data/index.js'

export default function Home({ onNavigate }) {
  const [formula, setFormula] = useState(0)
  const showcase = [
    { f: 'C₆H₁₂O₆ + 6 O₂ → 6 CO₂ + 6 H₂O + ~32 ATP', label: 'cellular respiration — your body, right now' },
    { f: '6 CO₂ + 6 H₂O + light → C₆H₁₂O₆ + 6 O₂', label: 'photosynthesis — the reaction that feeds Earth' },
    { f: 'pH = −log₁₀[H⁺]', label: 'why your blood must hold pH 7.4 or fail' },
    { f: 'Stage 3 neuron → Stage 1 (partial reprogramming, research)', label: 'the rejuvenation frontier' }
  ]
  React.useEffect(() => {
    const t = setInterval(() => setFormula((f) => (f + 1) % showcase.length), 3200)
    return () => clearInterval(t)
  }, [showcase.length])

  return (
    <div className="page home-page">
      <section className="hero">
        <div className="hero-orbs"><span /><span /><span /></div>
        <h1>Where <span className="grad-bio">Biology</span> meets <span className="grad-chem">Chemistry</span></h1>
        <p className="hero-sub">
          BioChem Lab generates structured formula cards for anything living or molecular — how it works, where in the
          body it happens, the problem, the solution, with diagrams and interactive 3-D models. Built for learning
          the real science, head to toe, microbe to mammal.
        </p>
        <div className="hero-actions">
          <button className="btn btn-primary btn-lg" onClick={() => onNavigate('studio')}>Open the Formula Studio →</button>
          <button className="btn btn-ghost btn-lg" onClick={() => onNavigate('models')}>View 3-D models</button>
        </div>
        <div className="hero-formula">
          <code>{showcase[formula].f}</code>
          <span>{showcase[formula].label}</span>
        </div>
      </section>

      <section className="section-cards">
        <h2>Five doors into the science</h2>
        <div className="sc-grid">
          {SECTIONS.map((s) => (
            <button key={s.id} className="sc-card" style={{ '--accent': s.accent }} onClick={() => onNavigate(`section:${s.id}`)}>
              <span className="sc-icon">{s.icon}</span>
              <h3>{s.name}</h3>
              <p>{s.blurb}</p>
              <span className="sc-count">{entriesFor(s.id).length} deep-dive topics</span>
            </button>
          ))}
          <button className="sc-card sc-card-alt" onClick={() => onNavigate('gallery')}>
            <span className="sc-icon">🖼️</span>
            <h3>Community Gallery</h3>
            <p>Formula cards generated by users, saved to a shared Supabase gallery.</p>
            <span className="sc-count">requires Supabase</span>
          </button>
        </div>
      </section>

      <section className="how-it-works">
        <h2>How the Formula Studio works</h2>
        <div className="hiw-steps">
          <div className="hiw-step"><span className="hiw-num">1</span><h4>Set your body profile</h4><p>Age, weight, height — used for educational estimates like blood volume, body water and metabolic rate, so every answer is personalized.</p></div>
          <div className="hiw-step"><span className="hiw-num">2</span><h4>Ask anything</h4><p>“How can a neuron go back to its first stage?” · “Generate a hybrid analysis for tiger and horse” · “How do kidneys filter blood?”</p></div>
          <div className="hiw-step"><span className="hiw-num">3</span><h4>Get a full formula card</h4><p>The formula, the mechanism step by step, where it works in the body, the problem, the solution, applications — with diagrams.</p></div>
          <div className="hiw-step"><span className="hiw-num">4</span><h4>See it in 3-D</h4><p>Explore the DNA helix and the myelinated neuron as interactive 3-D models you can rotate and zoom.</p></div>
        </div>
      </section>
    </div>
  )
}
